on: "push"
jobs:
  test_flagsmith:
    runs-on: ubuntu-latest
    container: node:lts-bookworm
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: ./src/flagsmith/aws_param
        with:
          FLAG_NAME: "test"
          FLAGSMITH_CLIENT_KEY: ${{Secrets.FLAGSMITH_CLIENT_KEY}}